### ISSUE TITLE
Error playactivity

### ISSUE THREAD

**Issue by lordmen99** [EasyDSS/EasyPlayer-RTMP-Android#1]
p E/CrashReport: sys default last handle start!
02-06 10:31:34.979 6935-6935/org.easydarwin.easyplayer.rtmp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: org.easydarwin.easyplayer.rtmp, PID: 6935
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{org.easydarwin.easyplayer.rtmp/org.easydarwin.easyplayer.PlayActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: You must supply a layout_height attribute.

fix it please

**Comment by milkywayriver** [comment]
没有重现.
